<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EKek5yV' shared service.

return $this->privates['.service_locator.EKek5yV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AbonneController::delete' => ['privates', '.service_locator.4FrMiJS', 'get_ServiceLocator_4FrMiJSService.php', true],
    'App\\Controller\\AbonneController::edit' => ['privates', '.service_locator.4FrMiJS', 'get_ServiceLocator_4FrMiJSService.php', true],
    'App\\Controller\\AbonneController::show' => ['privates', '.service_locator.4FrMiJS', 'get_ServiceLocator_4FrMiJSService.php', true],
    'App\\Controller\\AbonneController:delete' => ['privates', '.service_locator.4FrMiJS', 'get_ServiceLocator_4FrMiJSService.php', true],
    'App\\Controller\\AbonneController:edit' => ['privates', '.service_locator.4FrMiJS', 'get_ServiceLocator_4FrMiJSService.php', true],
    'App\\Controller\\AbonneController:show' => ['privates', '.service_locator.4FrMiJS', 'get_ServiceLocator_4FrMiJSService.php', true],
], [
    'App\\Controller\\AbonneController::delete' => '?',
    'App\\Controller\\AbonneController::edit' => '?',
    'App\\Controller\\AbonneController::show' => '?',
    'App\\Controller\\AbonneController:delete' => '?',
    'App\\Controller\\AbonneController:edit' => '?',
    'App\\Controller\\AbonneController:show' => '?',
]);
