<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4FrMiJS' shared service.

return $this->privates['.service_locator.4FrMiJS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'abonne' => ['privates', '.errored..service_locator.4FrMiJS.App\\Entity\\Abonne', NULL, 'Cannot autowire service ".service_locator.4FrMiJS": it references class "App\\Entity\\Abonne" but no such service exists.'],
], [
    'abonne' => 'App\\Entity\\Abonne',
]);
