<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU5NLGrS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU5NLGrS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU5NLGrS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU5NLGrS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU5NLGrS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U5NLGrS',
    'container.build_id' => 'adfba650',
    'container.build_time' => 1574112535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU5NLGrS');
