<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNmUZ3xJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNmUZ3xJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNmUZ3xJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNmUZ3xJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNmUZ3xJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NmUZ3xJ',
    'container.build_id' => '955711b4',
    'container.build_time' => 1574336198,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNmUZ3xJ');
