<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYGBN2JA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYGBN2JA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYGBN2JA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYGBN2JA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYGBN2JA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YGBN2JA',
    'container.build_id' => 'c7206d97',
    'container.build_time' => 1574282841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYGBN2JA');
